- name: install prerequisites
  shell: apt update && apt install libnl-genl-3-200 -y && apt install libnl-utils -y

- name: create folder
  file:
    path: /falcon
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download falcon-sensor
  shell:
    chdir: /falcon
    cmd: wget http://10.0.21.40/falcon-sensor_6.53.0-15003_amd64.deb

- name: carbon black install falcon-sensor
  shell:
    chdir: /falcon
    cmd: dpkg -i falcon-sensor_6.53.0-15003_amd64.deb

- name: carbon black falcon-sensor start with Customer ID
  shell:
    cmd: /opt/CrowdStrike/falconctl -s --cid=F63837EE707D490AA1029B785AB2D248-91

- name: fix dependency issues
  shell:
    cmd: apt --fix-broken install -y

- name: enable falcon-sensor
  shell: systemctl enable falcon-sensor

- name: start falcon-sensor
  shell: systemctl start falcon-sensor


